version: "3"
services:

  nexus:
    image: sonatype/nexus3:3.2.0
    ports:
      - 9002:8081
    volumes:
      - $HOME/Documents/nexus-data:/nexus-data

  jenkins:
    image: jenkins/jenkins
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - $HOME/Documents/jenkins:/var/jenkins_home
    depends_on:
      - nexus
    environment:
      - "JAVA_OPTS=-Duser.timezone=Europe/Berlin"

  nginx:
    image: nginx
    ports:
      - 9003:80
    volumes:
      - $HOME/Documents/websites:/usr/share/nginx/html:ro
      - $HOME/Documents/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  eureka:
    image: daveajlee/eureka-server
    ports:
      - 8761:8761

  spring-boot-admin-server:
    image: daveajlee/spring-boot-admin-server
    ports:
      - 8762:8762
